package com.streaming.simulation_service.kafka.producer;

import com.streaming.simulation_service.model.event.MatchEvent;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.stereotype.Component;

/**
 * Produces simulated match events to the configured Kafka topic.
 *
 * <p>This component is responsible for publishing {@link MatchEvent} payloads generated by the
 * simulation engine into Kafka for downstream consumers such as analytics, game services, or
 * real-time dashboards. It is intentionally small and focused so the simulation logic can remain
 * decoupled from the Kafka transport configuration.</p>
 *
 * @see MatchEvent
 * @see KafkaTemplate
 */
@Component
public class MatchEventProducer {

    /**
     * Kafka topic name used for publishing simulated match events.
     *
     * <p>The value is resolved from configuration using the property
     * {@code simulation.kafka.match-event-topic}.</p>
     */
    @Value("${simulation.kafka.match-event-topic}")
    private String matchEventTopic;

    /**
     * Spring Kafka template used for publishing messages to Kafka topics.
     */
    private final KafkaTemplate<String, MatchEvent> kafkaTemplate;

    /**
     * Create a new {@code MatchEventProducer} with the configured Kafka template.
     *
     * @param kafkaTemplate the Spring Kafka template used to send {@link MatchEvent}'s to Kafka.
     */
    public MatchEventProducer(KafkaTemplate<String, MatchEvent> kafkaTemplate) {
        this.kafkaTemplate = kafkaTemplate;
    }

    /**
     * Publish a simulated {@link MatchEvent} to the configured Kafka topic.
     *
     * <p>The event key is the string representation of the match id so Kafka partitions can be
     * grouped by match, which helps maintain ordering for a given match stream.</p>
     *
     * @param matchEvent the {@link MatchEvent} to publish; must not be {@code null}.
     */
    public void publishMatchEvent(MatchEvent matchEvent) {
        if (matchEvent != null) {
            kafkaTemplate.send(matchEventTopic, matchEvent.matchId().toString(), matchEvent);
        }
    }
}
